backend:
  repo: bibbox/bibbox-website
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://api.github.com
  # the following 2 are unsure, read here for more: https://decapcms.org/docs/backends-overview/
  site_domain: bibbox.bbmri-eric.eu
  base_url: /admin
media_folder: static/img
public_folder: /img
# the folling structure is the base template for the admin panel, but not the real one
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }